<div class="row-fluid">
    <div class="span12">
        <a class="btn btn-success pull-right" href="<?php echo $this->url( 'reportorderbook', array( 'action' => 'exportquarterlyorderbook', 'year' => $year, 'month' => $quarter ) ); ?>">Download CSV</a>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <table class="table table-bordered">
            <tr>
                <th>Rating</th>
                <th>Reference</th>
                <th>Project</th>
                <th>Customer</th>
                <th>Project Value</th>
                <th>Owner</th>
                <th>Started</th>
                <th>Completed</th>
            </tr>
            <?php if ( !empty($data) ): ?>
                <?php $total = 0; ?>
                <?php foreach ( $data as $key => $value ): ?>
                    <tr>
                        <?php
                        $ratingColor = '#fff';
                        switch ( $value['rating'] )
                        {
                            case 9: // Red Rated
                                $ratingColor = '#DE577B';
                                break;
                            case 8: // Amber Rated
                                $ratingColor = '#F37B53';
                                break;
                            case 7: // Green Rated
                                $ratingColor = '#0CA389';
                                break;
                            default:
                                $ratingColor = '#fff';
                        }
                        ?>
                        <td style="background-color:<?php echo $ratingColor; ?>;text-align:center;color:#fff;">
                            <strong>
                                <?php
                                if ( $value['project_status_id'] == 1 )
                                {
                                    echo 'P';
                                }
                                elseif ( $value['project_status_id'] >= 40 && $value['project_satus_id'] <= 100 )
                                {
                                    echo 'J';
                                }
                                elseif ( $value['project_status_id'] == 600 )
                                {
                                    echo 'L';
                                }
                                ?>
                            </strong>
                        </td>
                        <td nowrap="nowrap"><?php echo str_pad( $value['client_id'], 5, "0", STR_PAD_LEFT ) . '-' . str_pad( $value['project_id'], 5, "0", STR_PAD_LEFT ) ?></td>
                        <td><a href="<?php echo $this->url( 'project', Array( 'cid' => $value['client_id'], 'pid' => $value['project_id'] ) ); ?>"> <?php echo $value['project_name'] ?></a></td>
                        <td><a href="<?php echo $this->url( 'client', Array( 'id' => $value['client_id'] ) ); ?>"><?php echo $value['client_name']; ?></a></td>
                        <td style="text-align:right !important;">&#163; <?php echo number_format( $value['price'], 2 ); ?></td>
                        <td><?php echo $value['user_name']; ?></td>
                        <td nowrap="nowrap"><?php echo date( 'd M, Y', strtotime( $value['contracted'] ) ); ?></td>
                        <td nowrap="nowrap"><?php echo empty($value['completed']) ? 'Date not set' : date( 'd M, Y', strtotime( $value['completed'] ) ); ?></td>
                    </tr>
                    <?php $total += $value['price']; ?>
                <?php endforeach; ?>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td style="text-align:right;"><strong>Total Value</strong></td>
                    <td style="text-align:right;">&#163;<?php echo number_format( $total, 2 ); ?></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>

            <?php else: ?>
                <tr>
                    <td colspan="8">
                        No record found
                    </td>
                </tr>
            <?php endif; ?>
        </table>
    </div>
</div>

