<?php

$client = $project->getClient();
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
$this->headLink()
    ->appendStylesheet( '/assets/uniform/css/uniform.default.css' )
    ->appendStylesheet( '/assets/data-tables/DT_bootstrap.css' )
    ->appendStylesheet( '/assets/chosen-bootstrap/chosen/chosen.css' )
    ->appendStylesheet( '/assets/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css' )
    ->appendStylesheet( '/assets/bootstrap-datepicker/css/datepicker.css' );

$this->inlineScript()
    ->appendFile( '/assets/data-tables/jquery.dataTables.js' )
    ->appendFile( '/assets/data-tables/DT_bootstrap.js' )
    ->appendFile( '/assets/bootstrap-datepicker/js/bootstrap-datepicker.js' )
    ->appendFile( '/assets/chosen-bootstrap/chosen/chosen.jquery.min.js' )
    ->appendFile( '/assets/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js' )
    ->appendFile( '/js/jquery.validate.min.js' )
    ->appendFile( '/js/forms/job/resources.js' );

$this->inlineScript()->captureStart();

echo <<<JS
    $(function(){
        var resourceTable = $('#resources_tbl').dataTable({
            "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
            "bProcessing": true,
            "bPaginate": false,
            "bFilter": false,
            "bInfo": false,
            sAjaxSource: "/client-{$client->getClientId()}/job-{$project->getProjectId()}/resourcelist/",
            "aoColumns" : [
                null,
                null,
                null,
                null,
                null,
                {"sClass": "center"},
                {"sClass": "right"},
                {"sClass": "right"},
                { 'bSortable': false }
            ]
        });

        var invoiceTable = $('#invoices_tbl').dataTable({
            "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
            "bProcessing": true,
            "bPaginate": false,
            "bFilter": false,
            "bInfo" : false,
            sAjaxSource: "/client-{$client->getClientId()}/job-{$project->getProjectId()}/invoicelist/",
            "aoColumns" : [
                null,
                null,
                null,
                {"sClass": "right"},
                { 'bSortable': false }
            ]
        });


        $('#btn-close-invoice, #btn-close-product, #btn-close-resource ').on('click', function(){
            window.location.reload();
        });

        $('.btn-remove-invoice').live('click', function(){
            var id = $(this).attr('data-id');
            if ( confirm('Are you sure to delete this record!') )
            {
                var params = 'ts='+Math.round(new Date().getTime()/1000);
                $.ajax({
                    type: 'POST',
                    url: '/resource-activity/resource-' + id + '/remove',
                    data: params, // Just send the Base64 content in POST body
                    processData: true, // No need to process
                    timeout: 60000, // 1 min timeout
                    dataType: 'text', // Pure Base64 char data
                    beforeSend: function onBeforeSend(xhr, settings) {},
                    error: function onError(XMLHttpRequest, textStatus, errorThrown) {},
                    success: function onUploadComplete(response) {
                        try{
                            var obj=jQuery.parseJSON(response);
                            var k = 0;
                            // an error has been detected
                            if (obj.err == true) {

                            } else{ // no errors
                                growl('Success!', 'The resource activity has been deleted successfully.', {time: 3000});
                                window.location.reload();
                            }
                        }
                        catch(error){
                        }
                    },
                });
            }
            else
            {
                return false;
            }
        });

    });
JS;
$this->inlineScript()->captureEnd();
$this->headStyle()->captureStart();
?>
th.center, td.center{
text-align:center!important;
}
th.right, td.right{
text-align:right!important;
}
th.right{
padding-right:20px;
}
<?php $this->headStyle()->captureEnd(); ?>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN BASIC PORTLET-->
        <div class="widget purple">
            <div class="widget-title">
                <h4><i class="icon-barcode"></i> Resource Activities</h4>
            <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
            </span>
            </div>
            <div class="widget-body">
                <?php if ( $this->isGranted( 'project.write' ) )
                { ?>
                    <div class="pull-left">
                        <a class="btn green linkable" href="javascript:" id="btn-add-activity-modal">
                            Add Activity <i class="icon-plus"></i>
                        </a>
                        &nbsp;
                        <a class="btn green linkable" href="javascript:" id="btn-add-product-modal">
                            Add Product <i class="icon-plus"></i>
                        </a>
                        &nbsp;
                        <a class="btn green linkable" href="javascript:" id="btn-add-invoice-modal">
                            Add Invoice <i class="icon-plus"></i>
                        </a>
                    </div>
                <?php } ?>
                <div class="btn-group pull-right">
                    <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="icon-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right">
                        <li><a href="javascript:">Export to Excel</a></li>
                    </ul>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        <?php
                        $margin = $totals['invoices'] - $totals['others'];
                        if ( $totals['invoices'] > 0 )
                            $percentAge = ($margin / $totals['invoices']) * 100;
                        else
                            $percentAge = 0;
                        ?>
                        <p></p>

                        <p>
                            <strong>BILLED TO DATE:</strong> <span style="color:#e82013">£ <?php echo number_format( $totals['invoices'], 2 ); ?></span>
                            | <strong>COSTS TO DATE:</strong> <span style="color:#e82013">£ <?php echo number_format( $totals['others'], 2 ); ?></span>
                            | <strong>MARGIN:</strong> <span style="color:#e82013">£ <?php echo number_format( $margin, 2 ); ?> (<?php echo number_format( $percentAge, 2 ); ?>%)</span>
                        </p>

                        <table class="table table-striped table-bordered table-advance table-hover" id="invoices_tbl">
                            <caption><h2 class="pull-left">Invoices</h2></caption>
                            <thead>
                            <tr>
                                <th><i class="icon-calendar"></i> Date</th>
                                <th> Reference</th>
                                <th> Details</th>
                                <th> Amount</th>
                                <th style="width:100px;"></th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                            <tfoot>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>&#163;<?php echo number_format( $totals['invoices'], 2 ) ?></td>
                            </tr>
                            </tfoot>
                        </table>
                        <table class="table table-striped table-bordered table-advance table-hover" id="resources_tbl">
                            <caption><h2 class="pull-left">Resources</h2></caption>
                            <thead>
                            <tr>
                                <th><i class="icon-calendar"></i> Date</th>
                                <th> Reference</th>
                                <th> Details</th>
                                <th> Resource</th>
                                <th> Cost Code</th>
                                <th class="center"> Quantity</th>
                                <th> Rate</th>
                                <th> Total</th>
                                <th style="width:100px;"></th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                            <tfoot>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>&#163;<?php echo number_format( $totals['others'], 2 ) ?></td>
                            </tr>
                            </tfoot>
                        </table>

                    </div>
                </div>
            </div>
        </div>
        <!-- END BASIC PORTLET-->
    </div>
</div>
<?php echo $this->partial( 'partial/job/dialog/resource_add.phtml' ); ?>
<?php echo $this->partial( 'partial/job/dialog/resource_edit.phtml' ); ?>

<?php echo $this->partial( 'partial/job/dialog/invoice_add.phtml' ); ?>
<?php echo $this->partial( 'partial/job/dialog/invoice_edit.phtml' ); ?>

<?php echo $this->partial( 'partial/job/dialog/product_add.phtml' ); ?>
<?php echo $this->partial( 'partial/job/dialog/product_edit.phtml' ); ?>
