<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
$this->inlineScript()
    ->appendFile('/js/forms/tools/remotephosphor.js');


$phosphorColoursJS = array();
$phosphorColoursJSStr = '';
foreach ($phosphorColours as $color => $phosphorColour) {
    if (empty($phosphorColour)) {
        continue;
    }
    $data = array();
    foreach ($phosphorColour as $phosphorLength) {
        $data [] = "'{$phosphorLength[0]}': " . (empty($phosphorLength[1]) ? 'false' : 'true');
    }
    $phosphorColoursJS[] = "{$color}: {" . implode (', ', $data) . "}";
}

$phosphorColoursJSStr = '{' . implode(', ', $phosphorColoursJS) . '}';


$this->inlineScript()->captureStart();
echo <<<JS

function resetPhosphorDropdown(color, selected) {
    var phosphorProducts = {$phosphorColoursJSStr};

    $('form[name=RemotePhosphorForm] select[name=maximumPhosphorLength] option:not(.default)').remove();

    if (!phosphorProducts[color] || phosphorProducts[color].length < 1) {
        return;
    }

    var selectList = $('form[name=RemotePhosphorForm] select[name=maximumPhosphorLength]');
    for (var i in phosphorProducts[color]) {
        selectList.append($('<option>').val(i).text(i + (!!phosphorProducts[color][i] ? ' (default)': '')));
    }

    if (!!selected) {
        selectList.val(selected);
    }
}

$('form[name=RemotePhosphorForm] select[name=productId]').on('change', function(e) {
    var opt = $(this).find('option[value=' + $(this).val() + ']');
    if (opt == undefined) {
        return;
    }

    resetPhosphorDropdown(opt.attr('data-colour'));
});

JS;
$this->inlineScript()->captureEnd();
?>
<div class="widget blue" >
    <div class="widget-title">
        <h4><i class="icon-bar-chart"></i> Remote Phosphor Calculator</h4>
       <span class="tools">
           <a href="javascript:;" class="icon-chevron-down"></a>
           <a href="javascript:;" class="icon-remove"></a>
       </span>
    </div>
    <div class="widget-body relative" style="min-height: 400px;">
        <div id="remotePhosphorLoader" class="loader"></div>
        <?php echo $this->form()->openTag($formRemotePhosphor); ?>
        <div class="alert">
            Enter the required length and product type of the architectural LED and click on the calculate button to get a quick overview of achievable configurations.
        </div>
        <div class="row-fluid">
            <div class="span6">
                <div class="control-group">
                    <label class="control-label">Required Length</label>
                    <div class="controls">
                        <div class="input-append">
                            <?php echo $this->formElement($formRemotePhosphor->get('length'));  ?>
                            <span class="add-on">mm</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="span6">
                <div class="control-group">
                    <label class="control-label">Maximum Unit Length</label>
                    <div class="controls">
                        <div class="input-append">
                            <input name="maxunitlen" type="text" data-original-title="Maximum configurable unit length for architectural length" data-trigger="hover" class="span6  tooltips" value="5000">                                            <span class="add-on">mm</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <div class="control-group">
                    <label class="control-label">Product</label>
                    <div class="controls">
                        <select class="span12" name="productId" data-placeholder="Select Product">
                            <option></option>
                            <?php
                            $group = null;
                            if (!empty($products)) {
                                foreach ($products as $product) {
                                    if ($product['typeId'] != 3) { // service item should not be displayed here
                                        continue;
                                    }
                                    echo '<option value="' . $product['productId'] . '" ' .
                                        'data-ppu="' . $product['ppu'] . '" ' .
                                        'data-pwr="' . round($product['pwr'], 0) . '" ' .
                                        'data-colour="' . round($product['colour'], 0) . '" ' .
                                        'data-type="' . $product['type'] . '" ' .
                                        'data-brand="' . $product['brand'] . '" ' .
                                        'data-eca="' . (!empty($product['eca']) ? 1 : 0) . '" ' .
                                        '>' . $product['model'] . '</option>';
                                }
                            }
                            ?>
                        </select>
                    </div>
                </div>
            </div>
            <div class="span6">
                <div class="control-group">
                    <label class="control-label">Phosphor Length</label>

                    <div class="controls">
                        <select name="maximumPhosphorLength" class="span12">
                            <option class="default" value="">Use Default Length</option>
                        </select>
                    </div>
                </div>

            </div>
        </div>


        <button class="btn btn-success pull-right" id="btn-remotephosphor-calculate"><i class="icon-bar-chart"></i> Calculate</button>
        <div class="clearfix"></div>
        <hr />
        <table class="table">
            <tbody>
                <tr>
                    <th style="width: 150px">Achievable Length</th>
                    <td id="info-rp-deliverable">-</td>
                </tr>
                <tr>
                    <th>Billable Units</th>
                    <td id="info-rp-billable">-</td>
                </tr>
                <tr>
                    <th>Configuration</th>
                    <td id="info-rp-config">-</td>
                </tr>
            </tbody>
        </table>
        <?php echo $this->form()->closeTag($formRemotePhosphor); ?>
        <span id="info-rp-error" class="label label-important" style="position: absolute; left: 10px; bottom: 10px; display: none">Error: Please check the details</span>
        <a href="/tools/rpcalculator/" class="pull-right" style="position: absolute; right: 10px; bottom: 10px">View Advanced Tool <i class="icon-double-angle-right"></i></a>
    </div>
</div>