<?php
echo $this->partial( 'partial/report/sales/orderbookquarterlychart.phtml' );
?>
<div class="row-fluid">
    <div class="span12">
        <h3>Order Book by Value</h3>
        <table class="table table-bordered table-responsive">
            <?php foreach ( $data['value'] as $key => $value ): ?>
                <tr>
                    <td nowrap="nowrap" style="text-align:right;">
                        <?php if ( $key != 'Year' ): ?>
                            <a href="<?php echo $this->url( 'reportorderbook', array( 'action' => 'quarterlyList', 'year' => $key ) ) ?>">
                                <?php echo $key . ' - ' . ($key + 1); ?>
                            </a>
                        <?php else: ?>
                            <?php echo $key; ?>
                        <?php endif; ?>
                    </td>
                    <td nowrap="nowrap" style="text-align:right;">
                        <?php if ( is_numeric( $key ) ): ?>
                            <a href="<?php echo $this->url( 'reportorderbook', array( 'action' => 'quarterlyList', 'year' => $key, 'month' => 2  ) ) ?>">
                                <?php echo $value[0]; ?>
                            </a>
                        <?php else: ?>
                            <?php echo $value[0]; ?>
                        <?php endif; ?>
                    </td>
                    <td nowrap="nowrap" style="text-align:right;">
                        <?php if ( is_numeric( $key ) ): ?>
                            <a href="<?php echo $this->url( 'reportorderbook', array( 'action' => 'quarterlyList', 'year' => $key, 'month' => 3  ) ) ?>">
                                <?php echo $value[1]; ?>
                            </a>
                        <?php else: ?>
                            <?php echo $value[1]; ?>
                        <?php endif; ?>
                    </td>
                    <td nowrap="nowrap" style="text-align:right;">
                        <?php if ( is_numeric( $key ) ): ?>
                            <a href="<?php echo $this->url( 'reportorderbook', array( 'action' => 'quarterlyList', 'year' => $key, 'month' => 4  ) ) ?>">
                                <?php echo $value[2]; ?>
                            </a>
                        <?php else: ?>
                            <?php echo $value[2]; ?>
                        <?php endif; ?>
                    </td>
                    <td nowrap="nowrap" style="text-align:right;">
                        <?php if ( is_numeric( $key ) ): ?>
                            <a href="<?php echo $this->url( 'reportorderbook', array( 'action' => 'quarterlyList', 'year' => $key, 'month' => 1  ) ) ?>">
                                <?php echo $value[3]; ?>
                            </a>
                        <?php else: ?>
                            <?php echo $value[3]; ?>
                        <?php endif; ?>
                    </td>

                    <td nowrap="nowrap" style="text-align:right;">
                        <?php if ( $value[4] != 'Total' ): ?>
                            &#163;<?php echo number_format( $value[4], 0 ); ?>
                        <?php else: ?>
                            <?php echo $value[4]; ?>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>
<br/>
<br/>
<div class="row-fluid">
    <div class="span12">
        <h3>Order Book by Value</h3>
        <table class="table table-bordered table-responsive">
            <?php foreach ( $data['count'] as $key => $value ): ?>
                <tr>
                    <td nowrap="nowrap" style="text-align:right;">
                        <?php if ( $key != 'Year' ): ?>
                            <a href="<?php echo $this->url( 'reportorderbook', array( 'action' => 'quarterlyList', 'year' => $key ) ) ?>">
                                <?php echo $key . ' - ' . ($key + 1); ?>
                            </a>
                        <?php else: ?>
                            <?php echo $key; ?>
                        <?php endif; ?>
                    </td>
                    <td nowrap="nowrap" style="text-align:right;">
                        <?php if ( is_numeric( $key ) ): ?>
                            <a href="<?php echo $this->url( 'reportorderbook', array( 'action' => 'quarterlyList', 'year' => $key, 'month' => 2 ) ) ?>">
                                <?php echo $value[0]; ?>
                            </a>
                        <?php else: ?>
                            <?php echo $value[0]; ?>
                        <?php endif; ?>
                    </td>
                    <td nowrap="nowrap" style="text-align:right;">
                        <?php if ( is_numeric( $key ) ): ?>
                            <a href="<?php echo $this->url( 'reportorderbook', array( 'action' => 'quarterlyList', 'year' => $key, 'month' => 3  ) ) ?>">
                                <?php echo $value[1]; ?>
                            </a>
                        <?php else: ?>
                            <?php echo $value[1]; ?>
                        <?php endif; ?>
                    </td>
                    <td nowrap="nowrap" style="text-align:right;">
                        <?php if ( is_numeric( $key ) ): ?>
                            <a href="<?php echo $this->url( 'reportorderbook', array( 'action' => 'quarterlyList', 'year' => $key, 'month' => 4  ) ) ?>">
                                <?php echo $value[2]; ?>
                            </a>
                        <?php else: ?>
                            <?php echo $value[2]; ?>
                        <?php endif; ?>
                    </td>
                    <td nowrap="nowrap" style="text-align:right;">
                        <?php if ( is_numeric( $key ) ): ?>
                            <a href="<?php echo $this->url( 'reportorderbook', array( 'action' => 'quarterlyList', 'year' => $key, 'month' => 1  ) ) ?>">
                                <?php echo $value[3]; ?>
                            </a>
                        <?php else: ?>
                            <?php echo $value[3]; ?>
                        <?php endif; ?>
                    </td>
                    <td nowrap="nowrap" style="text-align:right;">
                        <?php if ( $value[4] != 'Total' ): ?>
                            <?php echo number_format( $value[4], 0 ); ?>
                        <?php else: ?>
                            <?php echo $value[4]; ?>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>