<?php
$url = $this->url( 'reports', array( 'action' => 'ajaxProduct', 'group' => 'client', 'report' => 7 ) );
$this->inlineScript()->captureStart();
echo <<<JS
function numberWithCommas(x) {
    return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}

$(document).ready(function(){

    $('#downloadProducts').on('click', function(){
        if ( $('#product_id').val() == '' )
        {
            alert('Please filter products first to download filtered csv file.');
            return false;
        }
    });


    $('#btnProductReport').on( 'click', function(e){
        e.preventDefault();
        e.stopPropagation();

        var prod_id = $('#product_id').val();
        var url = '/reportproduct/downloadFilteredProduct/7/' + prod_id;
        $('#downloadProducts').prop( 'href', url );


        $('#productLoader').fadeIn(function(){
            $.ajax({
                type: 'post',
                url: "$url",
                data: {'product_id': $('#product_id').val()},
                dataType: 'json',
                beforeSend:function(){
                    $('#table-body').empty();
                },
                success:function(response){
                    //var stats = response.stats;

                    for( var key in response )
                    {
                        var html = '<tr>';
                            html += '<td>' + response[key].product_id + '</td>';
                            html += '<td>' + response[key].model + '</td>';
                            html += '<td>' + response[key].description + '</td>';
                            html += '<td style="text-align:right!important;" nowrap="nowrap">&#163; ' + numberWithCommas( response[key].cpu ) + '</td>';
                            html += '<td style="text-align:right!important;" nowrap="nowrap">&#163; ' + numberWithCommas( response[key].ppu ) + '</td>';
                            html += '<td  nowrap="nowrap">' + numberWithCommas( response[key].added ) + '</td>';
                        html += '</tr>';
                        $('#table-body').append(html);
                    }
                },
                complete: function(){
                    $('#productLoader').fadeOut();
                }

            });
        });
    });
});
JS;
$this->inlineScript()->captureEnd();

?>
<div id="productLoader" class="loader"></div>
<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th colspan="5">Product Id: <input type="text" name="product_id" id="product_id" value=""/>
            <button class="btn btn-default" id="btnProductReport">Get Products From</button>
            <a href="<?php echo $this->url('exportproducts', array( 'action' => 'downloadFilteredProduct', 'report' => 7, 'product_id' => ''  )); ?>" id="downloadProducts">Download Filtered Products</a>
            <span id="loading-data" style="display:none;"><img src="<?php echo $this->basePath( '/img/ajax-loader.gif' ); ?>" width="20" align="middle"/> Loading</span>
        </th>
    </tr>
    <tr>
        <th>Product Id</th>
        <th>Model</th>
        <th>Description</th>
        <th>CPU</th>
        <th>PPU</th>
        <th>Added</th>
    </tr>
    </thead>
    <tbody id="table-body">
    <?php foreach ( $data as $product ): ?>
        <tr>
            <td><?php echo $product->getProductId(); ?></td>
            <td><?php echo $product->getModel(); ?></td>
            <td><?php echo $product->getDescription(); ?></td>
            <td style="text-align:right;" nowrap="nowrap">&#163; <?php echo number_format( $product->getCpu(), 2 ); ?></td>
            <td style="text-align:right" nowrap="nowrap">&#163; <?php echo number_format( $product->getPpu(), 2 ); ?></td>
            <td nowrap="nowrap"><?php echo $product->getCreated()->format( 'd M, Y h:i A' ); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>