version: '2'
services:
    web8p3:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ../:/var/www
        ports:
            - "8090:80"
        links:
            - app8p3
    app8p3:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ../:/var/www
        links:
            - database8p3
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database8p3"
    database8p3:
        image: mysql:5.6
        environment:
            - "MYSQL_ROOT_PASSWORD=2@2h31EYU1^g"
            - "MYSQL_DATABASE=8point3"
            - "MYSQL_USER=8point3"
            - "MYSQL_PASSWORD=r09m9D!GF9&7"
        ports:
            - "33062:3306"
