<div class="row-fluid">
    <div class="span12">
        <a class="btn btn-success pull-right" href="<?php echo $this->url( 'reportquarterly', array( 'action' => 'quotations', 'quarter' => $quarter, 'year' => $year, 'export' => 'csv' ) ); ?>">Download CSV</a>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <table class="table table-bordered">
            <tr>
                <th>Document ID</th>
                <th>Project Name</th>
                <th>Client</th>
                <th>Value</th>
                <th>Margin</th>
                <th>Owner</th>
                <th>Date</th>
            </tr>
            <?php if ( !empty($quotations) ): ?>
                <?php foreach ( $quotations as $quotation ): ?>

                    <tr>
                        <td><?php echo $quotation['document_list_id']; ?></td>
                        <td><a href="<?php echo $this->url( 'project', Array( 'cid' => $quotation['client_id'], 'pid' => $quotation['project_id'] ) ); ?>"><?php echo $quotation['project_name'] ?> - (<?php echo $quotation['project_id']; ?>)</a></td>
                        <td><a href="<?php echo $this->url( 'client', Array( 'id' => $quotation['client_id'] ) ); ?>"><?php echo $quotation['client_name']; ?> - (<?php echo $quotation['client_id']; ?>)</a></td>
                        <td style="text-align:right!important;" nowrap="nowrap">&#163; <?php echo $quotation['figures']['cost']; ?></td>
                        <td nowrap="nowrap">
                            <?php
                            $tmpPpuTotal = $quotation['figures']['cost'];
                            $tmpCpuTotal = $quotation['cost'];
                            if ( $tmpPpuTotal )
                            {
                                $prjMargin = (($tmpPpuTotal - $tmpCpuTotal) / $tmpPpuTotal) * 100;
                                echo number_format( $prjMargin, 2 ) . " %";
                            }
                            else
                            {
                                echo '0 %';
                            }
                            ?>

                        </td>
                        <td><?php echo $quotation['user_name']; ?></td>
                        <td nowrap="nowrap"><?php echo date( 'd M, Y', strtotime( $quotation['created'] ) ); ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="6">
                        No record found
                    </td>
                </tr>
            <?php endif; ?>
        </table>
    </div>
</div>