<div class="row-fluid">
    <div class="span12">
        <a class="btn btn-success pull-right" href="<?php echo $this->url( 'reportquarterly', array( 'action' => 'wonprojects', 'quarter' => $quarter, 'year' => $year, 'export' => 'csv' ) ); ?>">Download CSV</a>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <table class="table table-bordered">
            <tr>
                <th>Reference</th>
                <th>Project</th>
                <th>Client</th>
                <th>Project Value</th>
                <th>Margin</th>
                <th>Owner</th>
                <th>Date</th>
            </tr>
            <?php if ( !empty($projects) ): ?>
                <?php $total = 0; ?>
                <?php foreach ( $projects as $key => $value ): ?>
                    <tr>
                        <td nowrap="nowrap"><?php echo str_pad( $value['client_id'], 5, "0", STR_PAD_LEFT ) . '-' . str_pad( $value['project_id'], 5, "0", STR_PAD_LEFT ) ?></td>
                        <td><a href="<?php echo $this->url( 'project', Array( 'cid' => $value['client_id'], 'pid' => $value['project_id'] ) ); ?>"> <?php echo $value['project_name'] ?></a></td>
                        <td><a href="<?php echo $this->url( 'client', Array( 'id' => $value['client_id'] ) ); ?>"><?php echo $value['client_name']; ?></a></td>
                        <td style="text-align:right !important;">&#163; <?php echo number_format( $value['figures']['cost'], 2 ); ?></td>
                        <td nowrap="nowrap">
                            <?php
                            $tmpPpuTotal = $value['figures']['cost'];
                            $tmpCpuTotal = $value['cost'];
                            if ( $tmpPpuTotal )
                            {
                                $prjMargin = (($tmpPpuTotal - $tmpCpuTotal) / $tmpPpuTotal) * 100;
                                echo number_format( $prjMargin, 2 ) . " %";
                            }
                            else
                            {
                                echo '0 %';
                            }
                            ?>

                        </td>
                        <td><?php echo $value['user_name']; ?></td>
                        <td><?php echo date( 'd M, Y', strtotime( $value['created'] ) ); ?></td>
                    </tr>
                    <?php $total += $value['figures']['cost']; ?>
                <?php endforeach; ?>
                <tr>
                    <td></td>
                    <td></td>
                    <td style="text-align:right;"><strong>Total Value</strong></td>
                    <td style="text-align:right;">&#163;<?php echo number_format( $total, 2 ); ?></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            <?php else: ?>
                <tr>
                    <td colspan="5">
                        No record found
                    </td>
                </tr>
            <?php endif; ?>
        </table>
    </div>
</div>
