<div id="modalJobStatus" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Job Status Information&nbsp;</h3>
    </div>
    <div class="modal-body">
        <div id="jobStatusLoader" class="loader"></div>
        <table class="table table-advance table-bordered">
            <thead>
            <tr>
                <th colspan="2" id="contact-name"></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td id="contact-company">
                    <label>Select the job status that best fits the job according to the viability, value and position of the opportunity.</label>
                    <div class="space15"></div>
                    <div class="control-group">
                        <form id="JobStatusForm" action="/client-<?php echo $project->getClient()->getClientId(); ?>/job<?php echo $route . '-' . $project->getProjectId(); ?>/updateStatus/" class="form-horizontal form-nomargin">
                            <label class="control-label">Job Status</label>
                            <div class="controls">
                                <select name="sltJobStatus" id="sltJobStatus">
                                    <option <?php echo $project->getRating() == 7 ? 'selected="selected"' : ''; ?> value="7">Active</option>
                                    <option <?php echo $project->getRating() == 8 ? 'selected="selected"' : ''; ?> value="8">Suspended</option>
                                    <option <?php echo $project->getRating() == 9 ? 'selected="selected"' : ''; ?> value="9">Completed</option>
                                </select>
                            </div>
                            <br/>
                            <label class="control-label">Date Started</label>
                            <div class="controls">
                                <div class="input-append " id="dpYears" data-date="12-02-2012" data-date-format="dd-mm-yyyy" >
                                    <input type="text" name="start_date" id="start_date" data-date-format="dd/mm/yyyy" value="<?php echo !empty($project->getContracted()) ? $project->getContracted()->format('d/m/Y') : ''; ?>" />
                                    <span class="add-on" id="startedDtIcon" style="cursor:pointer;" title="Reset date"><i class="icon-calendar"></i></span>
                                </div>
                            </div>
                            <br/>
                            <label class="control-label">Date Completed</label>
                            <div class="controls">
                                <div class="input-append " id="dpYears" data-date="12-02-2012" data-date-format="dd-mm-yyyy" >
                                    <input type="text" name="completed_date" id="completed_date" data-date-format="dd/mm/yyyy" value="<?php echo !empty($project->getCompleted()) ? $project->getCompleted()->format('d/m/Y') : ''; ?>" />
                                    <span class="add-on" id="completedDtIcon" style="cursor:pointer;" title="Reset date"><i class="icon-calendar"></i></span>
                                </div>
                            </div>
                            <br/>
                            <label class="control-label">Exclude from Reporting</label>
                            <div class="controls">
                                <input type="checkbox" name="exclude_from_reporting" id="exclude_from_reporting" <?php echo $project->getExcludeReporting() ?  'checked="checked"' :''; ?> value="1" />
                            </div>
                        </form>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
        <div id="msgs3"></div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Close</button>
        <button class="btn btn-success" id="btn-edit-status" aria-hidden="true"><i class="icon-save"></i> Save</button>
    </div>
</div>