<?php
$this->headLink()
    ->appendStylesheet( '/assets/uniform/css/uniform.default.css' )
    ->appendStylesheet( '/assets/data-tables/DT_bootstrap.css' )
    ->appendStylesheet( '/assets/chosen-bootstrap/chosen/chosen.css' )
    ->appendStylesheet( '/assets/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css' )
    ->appendStylesheet( '/assets/bootstrap-datepicker/css/datepicker.css' );

$this->inlineScript()
    ->appendFile( '/assets/bootstrap-datepicker/js/bootstrap-datepicker.js' )
    ->appendFile( '/assets/chosen-bootstrap/chosen/chosen.jquery.min.js' )
    ->appendFile( '/assets/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js' )
    ->appendFile( '/js/jquery.validate.min.js' )
    ->appendFile( '/js/jquery.blockui.js' )
    ->appendFile( '/assets/uniform/jquery.uniform.min.js' )
    ->appendFile( '/assets/data-tables/jquery.dataTables.js' )
    ->appendFile( '/assets/data-tables/DT_bootstrap.js' );

$this->headStyle()->captureStart(); ?>
#clients_tbl tbody td:nth-child(6){
text-align: center;
}

#clients_tbl tbody td{
vertical-align: middle;
}
<?php $this->headStyle()->captureEnd(); ?>

<?php $this->inlineScript()->captureStart();
echo <<<JS
$(function() {
    $('#btn-close-invoice, #btn-close-product, #btn-close-resource').on('click', function(){
        window.location.reload();
    });

    $('.btn-remove-cc').on('click', function(e){
        e.preventDefault();
        var url = $(this).attr('href');
        if ( confirm('Are you sure to delete?') == true )
        {
            window.location.href= url;
        }

        return false;
    });
});
JS;

$this->inlineScript()->captureEnd(); ?>
<?php if ( $this->flashMessenger()->render( 'success' ) ): ?>
    <div class="row-fluid">
        <div class="span12">
            <div class="alert alert-success">
                <?php echo $this->flashMessenger()->render( 'success' ); ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN EXAMPLE TABLE widget-->
        <div class="widget green">
            <div class="widget-title">
                <h4><i class="icon-2x"></i>Cost Codes</h4>
                    <span class="tools">
                        <a href="javascript:;" class="icon-chevron-down"></a>
                    </span>
            </div>
            <div class="widget-body">
                <a href="javascript:;" class="btn btn-default" id="btn-add-costcode-modal">Add Cost Codes <i class="icon icon-plus"></i></a>

                <div>
                    <div class="space15"></div>
                    <table class="table table-striped table-bordered table-hover" id="projects_tbl">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th style="width:85px;"></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if ( !empty($costcodes) ): ?>
                            <?php foreach ( $costcodes as $item ): ?>
                                <tr>
                                    <td nowrap="nowrap"><?php echo $item->getName(); ?></td>
                                    <td>
                                        <a href="javascript:;" data-id="<?php echo $item->getCostCodeId(); ?>" data-name="<?php echo $item->getName(); ?>" class="btn btn-success btn-edit-cost-code"><i class="icon-pencil"></i></a> &nbsp;
                                        <a href="/cost-code/item-<?php echo $item->getCostCodeId(); ?>/remove" class="btn btn-danger btn-remove-cc"><i
                                                class="icon-remove"></i></a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr>
                                <td colspan="2" style="text-align:center;">No Record found</td>
                            </tr>
                        <?php endif; ?>
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
        <!-- END EXAMPLE TABLE widget-->
    </div>
</div>
<?php echo $this->partial( 'partial/costcodes/dialogs/add.phtml' ); ?>
<?php echo $this->partial( 'partial/costcodes/dialogs/edit.phtml' ); ?>
<?php /*
<?php echo $this->partial( 'partial/resource/resource_edit.phtml' ); ?>

<?php echo $this->partial( 'partial/resource/product_add.phtml' ); ?>
<?php echo $this->partial( 'partial/resource/invoice_add.phtml' ); ?>
 */ ?>


