<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'ZfcRbac',
        'DoctrineModule',
        'DoctrineORMModule',
        'Application',
        'Assets',
        'Report',
        'Tools',
        'Trial',
        'Job',
        'Task',
        'User',
        'DOMPDFModule',
        'Space',
        'Login',
        'Project',
        'Client',
        'Product',
        'Contact',
        //'ZendDeveloperTools',
        'Sales',
        'Resource'
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor'
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php'
        )
    )
);
