<?php
$this->headLink()
    ->appendStylesheet( '/assets/uniform/css/uniform.default.css' )
    ->appendStylesheet( '/assets/data-tables/DT_bootstrap.css' )
    ->appendStylesheet( '/assets/chosen-bootstrap/chosen/chosen.css' )
    ->appendStylesheet( '/assets/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css' )
    ->appendStylesheet( '/assets/bootstrap-datepicker/css/datepicker.css' );

$this->inlineScript()
    ->appendFile( '/assets/bootstrap-datepicker/js/bootstrap-datepicker.js' )
    ->appendFile( '/assets/chosen-bootstrap/chosen/chosen.jquery.min.js' )
    ->appendFile( '/assets/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js' )
    ->appendFile( '/js/jquery.validate.min.js' )
    ->appendFile( '/js/jquery.blockui.js' )
    ->appendFile( '/assets/uniform/jquery.uniform.min.js' )
    ->appendFile( '/assets/data-tables/jquery.dataTables.js' )
    ->appendFile( '/assets/data-tables/DT_bootstrap.js' )
    ->appendFile('/js/forms/resources/resource.js');

$this->headStyle()->captureStart(); ?>
#clients_tbl tbody td:nth-child(6){
text-align: center;
}

#clients_tbl tbody td{
vertical-align: middle;
}
<?php $this->headStyle()->captureEnd(); ?>
<?php if ( $this->flashMessenger()->render( 'success' ) ): ?>
    <div class="row-fluid">
        <div class="span12">
            <div class="alert alert-success">
                <?php echo $this->flashMessenger()->render( 'success' ); ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN EXAMPLE TABLE widget-->
        <div class="widget green">
            <div class="widget-title">
                <h4><i class="icon-2x"></i>Resource - Add</h4>
                    <span class="tools">
                        <a href="javascript:;" class="icon-chevron-down"></a>
                    </span>
            </div>
            <div class="widget-body">
                <a href="javascript:;" class="btn btn-default" id="btn-add-resource">Add<i class="icon icon-plus"></i></a>

                <div>
                    <?php /*
                    <div class="clearfix">
                        <div class="btn-group pull-right">
                            <select name="fViewMode" id="fViewMode">
                                <option value="1">Show Owned &amp; Collaboration Jobs</option>
                                <option value="2">Show Owned Jobs Only</option>
                                <option value="3">Show Company Owned Jobs</option>
                                <?php if ( $this->isGranted( 'admin.all' ) )
                    { ?>
                                    <option value="4">Show All Jobs</option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    */ ?>
                    <div class="space15"></div>
                    <table class="table table-striped table-bordered table-hover" id="projects_tbl">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Cost Code</th>
                            <th>Unit</th>
                            <th style="text-align:right;">Cost</th>
                            <th width="100"></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if ( !empty($resources) ): ?>
                            <?php foreach ( $resources as $resource ): ?>
                                <!-- Hide Product and Invoice -->
                                <?php if ( $resource->getName() == 'Product' || $resource->getName() == 'Invoice' ) continue; ?>
                                <tr>
                                    <td nowrap="nowrap"><?php echo $resource->getName(); ?></td>
                                    <td nowrap="nowrap"><?php echo $resource->getCostCode()->getName(); ?></td>
                                    <td><?php echo $resource->getUnit(); ?></td>
                                    <td style="text-align:right;">&#163;<?php echo $resource->getCost(); ?></td>
                                    <td>
                                        <a href="javascript:;"
                                           data-rid="<?php echo $resource->getResourceId(); ?>"
                                           data-name="<?php echo $resource->getName(); ?>"
                                           data-costcode="<?php echo $resource->getCostCode()->getCostCodeId(); ?>"
                                           data-unit="<?php echo $resource->getUnit(); ?>"
                                           data-cost="<?php echo $resource->getCost(); ?>"
                                           class="btn btn-success btnResourceEdit">
                                            <i class="icon-pencil"></i>
                                        </a>

                                        <a href="javascript:;" data-rid="<?php echo $resource->getResourceId(); ?>" class="btn btn-danger btnResourceDelete"><i class="icon-remove"></i></a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr>
                                <td colspan="5" style="text-align:center;">No Record found</td>
                            </tr>
                        <?php endif; ?>
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
        <!-- END EXAMPLE TABLE widget-->
    </div>
</div>
<?php echo $this->partial( 'partial/resource/items/add.phtml' ); ?>
<?php echo $this->partial( 'partial/resource/items/edit.phtml' ); ?>

