<div id="modalRatingChart" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true" style="width:600px;">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Sales Rating Graph&nbsp;</h3>
    </div>
    <div class="modal-body">
          <div id="sales-chart-container" style="width:550px; height: 400px; margin: 0 auto"></div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Close</button>
    </div>
    <input type="hidden" name="user_id" id="user_id" value=""/>
</div>