<?php
namespace Resource\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;

use Zend\Json\Json;

use Application\Controller\AuthController;
use Zend\Mvc\MvcEvent;

class ActivitySpecificController extends AuthController
{
    /**
     *
     * @var Resource\Entity\ResourceActivity
     */
    private $activity;

    public function onDispatch( MvcEvent $e )
    {
        $rid = $this->params()->fromRoute( 'rid', '' ); //Resource Activity ID

        if ( empty($rid) )
        {
            return $this->redirect()->toRoute( 'resource_activities' );
        }

        $activity = $this->getEntityManager()->find( 'Resource\Entity\ResourceActivity', $rid );

        if ( !($activity instanceof \Resource\Entity\ResourceActivity) )
        {
            return $this->redirect()->toRoute( 'resource_activities' );
        }

        $this->setActivity( $activity );

        return parent::onDispatch( $e ); // TODO: Change the autogenerated stub
    }

    public function setActivity( \Resource\Entity\ResourceActivity $activity )
    {
        $this->activity = $activity;
        $this->getView()->setVariable( 'activity', $activity );

        return $this;
    }

    public function getActivity()
    {
        return $this->activity;
    }
}