<?php
namespace Resource\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;

use Zend\Json\Json;

use Application\Controller\AuthController;
use Zend\Mvc\MvcEvent;

class ResourceSpecificController extends AuthController
{
    /**
     *
     * @var Resource\Entity\Resource
     */
    private $resource;

    public function onDispatch( MvcEvent $e )
    {
        $rid = $this->params()->fromRoute( 'rid', '' ); //Resource Activity ID

        if ( empty($rid) )
        {
            return $this->redirect()->toRoute( 'resource_items' );
        }

        $resource = $this->getEntityManager()->find( 'Resource\Entity\Resource', $rid );

        if ( !($resource instanceof \Resource\Entity\Resource) )
        {
            return $this->redirect()->toRoute( 'resource_items' );
        }

        $this->setResource( $resource );

        return parent::onDispatch( $e ); // TODO: Change the autogenerated stub
    }

    public function setResource( \Resource\Entity\Resource $resource )
    {
        $this->resource = $resource;
        $this->getView()->setVariable( 'resource', $resource );

        return $this;
    }

    public function getResource()
    {
        return $this->resource;
    }
}