<?php
$this->headLink()
    ->appendStylesheet('/assets/uniform/css/uniform.default.css')
    ->appendStylesheet('/assets/data-tables/DT_bootstrap.css')
    ->appendStylesheet('/assets/chosen-bootstrap/chosen/chosen.css')
    ->appendStylesheet('/assets/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css')
    ->appendStylesheet('/assets/bootstrap-datepicker/css/datepicker.css');

$this->inlineScript()
    ->appendFile('/assets/bootstrap-datepicker/js/bootstrap-datepicker.js')
    ->appendFile('/assets/chosen-bootstrap/chosen/chosen.jquery.min.js')
    ->appendFile('/assets/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js')
    ->appendFile('/js/jquery.validate.min.js')
    ->appendFile('/js/jquery.blockui.js')
    ->appendFile('/assets/uniform/jquery.uniform.min.js')
    ->appendFile('/assets/data-tables/jquery.dataTables.js')
    ->appendFile('/assets/data-tables/DT_bootstrap.js')
    ->appendFile('/js/forms/resources/activity_list.js');


$this->headStyle()->captureStart(); ?>
#clients_tbl tbody td:nth-child(6){
text-align: center;
}

#clients_tbl tbody td{
vertical-align: middle;
}

.paging a, .paging span
{
display:inline-block;
padding:5px 10px;
border:1px solid #cccccc;
border-radius: 3px;
margin-right:5px;
}
.paging span{
background-color:#ccc;
}
.paging a:hover
{
background-color:#428bca;
color:#ffffff;
text-decoration: none;
}

.paging
{
text-align:left;
}
<?php $this->headStyle()->captureEnd(); ?>

<?php $this->inlineScript()->captureStart();
echo <<<JS
$(function() {
    $('#btn-close-invoice, #btn-close-product, #btn-close-resource').on('click', function(){
        window.location.reload();
    });
});
JS;

$this->inlineScript()->captureEnd(); ?>
<?php if ( $this->flashMessenger()->render('success') ): ?>
    <div class="row-fluid">
        <div class="span12">
            <div class="alert alert-success">
                <?php echo $this->flashMessenger()->render('success'); ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN EXAMPLE TABLE widget-->
        <div class="widget green">
            <div class="widget-title">
                <h4><i class="icon-2x"></i>Resource Activities</h4>
                    <span class="tools">
                        <a href="javascript:;" class="icon-chevron-down"></a>
                    </span>
            </div>
            <div class="widget-body">
                <a href="javascript:;" class="btn btn-default" id="btn-add-activity-modal">Add Activity <i class="icon icon-plus"></i></a>
                <a href="javascript:;" class="btn btn-default" id="btn-add-product-modal">Add Product <i class="icon icon-plus"></i></a>
                <a href="javascript:;" class="btn btn-default" id="btn-add-invoice-modal">Add Invoice <i class="icon icon-plus"></i></a>
                <a href="<?php echo $this->url('resource_items'); ?>" class="btn btn-default">Resource Items <i class="icon icon-list"></i></a>
                <a href="<?php echo $this->url('cost_codes'); ?>" class="btn btn-default">Cost Codes <i class="icon icon-list"></i></a>
                <a href="<?php echo $this->url('resource_activities', array('action' => 'activitysales')); ?>" class="btn btn-default">Activity With Sales <i class="icon icon-list"></i></a>

                <div>
                    <br/>

                    <div class="clearfix">
                        <div class="row-fluid">
                            <div class="span2">
                                <small class="pull-left">Filter Type:</small>
                                <br/>
                                <select name="filter_types" id="filter_types">
                                    <option value="">--Filter Activities--</option>
                                    <option value="wip">WIP (Work in progress)</option>
                                    <option value="cos">COS (Cost of sale)</option>
                                    <option value="invoice">Invoices</option>
                                </select>
                            </div>
                            <div class="span3">
                                <div class="row-fluid" style="display:none" id="cos_block">
                                    <div class="span5">
                                        <small>Completed Start Date:</small>
                                        <input type="text" style="width:120px;" name="cos_start_date" id="cos_start_date">
                                    </div>
                                    <div class="span5">
                                        <small>Completed End Date:</small>
                                        <input type="text" style="width:120px;" name="cos_start_date" id="cos_end_date">
                                    </div>
                                    <div class="span2">
                                        <br/>
                                        <input type="button" class="btn btn-default" id="btn_cos" value="Filter"/>
                                    </div>
                                </div>
                                <div class="row-fluid" style="display:none" id="invoice_block">
                                    <div class="span5">
                                        <small>Start Date:</small>
                                        <input type="text" style="width:120px;" name="invoice_start_date" id="invoice_start_date">
                                    </div>
                                    <div class="span5">
                                        <small>End Date:</small>
                                        <input type="text" style="width:120px;" name="invoice_start_date" id="invoice_end_date" value="<?php echo date('d-m-Y') ?>">
                                    </div>
                                    <div class="span2">
                                        <br/>
                                        <input type="button" class="btn btn-default" id="btn_invoice" value="Filter"/>
                                    </div>
                                </div>
                                <div class="row-fluid" style="display:none" id="wip_block">
                                    <div class="span10">
                                        Completed End Date: <br/>
                                        <input type="text" id="wip_end_date" name="wip_end_date">
                                    </div>
                                    <div class="span2">
                                        <br/>
                                        <input type="button" class="btn btn-default" id="btn_wip" value="Filter"/>
                                    </div>
                                </div>
                            </div>
                            <div class="span7">
                                <span class="pull-right"><a href="<?php echo $this->url('resource_activities', array('action'=> 'downloadActivities')); ?>" class="btn btn-success"><i class="icon-download-alt"></i> Download CSV</a></span>
                            </div>
                        </div>
                    </div>
                    <div class="space15"></div>
                    <table class="table table-bordered table-hover" id="projects_tbl">
                        <thead>
                        <tr>
                            <th>Date</th>
                            <th>Project Ref.</th>
                            <th>Reference</th>
                            <th style="width: 180px">Details</th>
                            <th style="width: 120px">Resource Type</th>
                            <th style="width: 120px">Resource</th>
                            <th style="width: 80px;">Cost Code</th>
                            <th style="width: 50px;text-align:right;">Quantity</th>
                            <th style="width: 50px;text-align:right;">Rate</th>
                            <th style="width: 150px;text-align:right;">Total Cost</th>
                            <th style="width: 35px;">&nbsp;</th>
                        </tr>
                        </thead>
                        <tbody id="activityRows">
                        <?php if ( !empty($data['activities']) ): ?>
                            <?php foreach ( $data['activities'] as $resource ): ?>
                                <tr style="background-color:<?php echo !empty($resource['color']) ? $resource['color'] : ''; ?>">
                                    <td nowrap="nowrap"><?php echo $resource['date']; ?></td>
                                    <td nowrap="nowrap">
                                        <a href="<?php echo $this->url('job', array('jid' => $resource['project']->getProjectId(), 'cid' => $resource['project']->getClient()->getClientId(), 'action' => 'resources')) ?>">
                                            <?php echo $resource['project_ref']; ?>
                                        </a>
                                    </td>
                                    <td>
                                        <?php if ( $resource['reference_type'] == 'product' ): ?>
                                            <a href="<?php echo $this->url('productitem', array('pid' => $resource['reference'])); ?>">
                                                <?php echo $resource['reference']; ?>
                                            </a>
                                        <?php else: ?>
                                            <?php echo $resource['reference']; ?>
                                        <?php endif; ?>
                                    </td>
                                    <td><?php echo $resource['details']; ?></td>
                                    <td><?php echo ucfirst($resource['reference_type']); ?></td>
                                    <td><?php echo $resource['resource']; ?></td>
                                    <td><?php echo $resource['cost_code']; ?></td>
                                    <td style="text-align:right;"><?php echo $resource['quantity']; ?></td>
                                    <td style="text-align:right;">&#163;<?php echo $resource['rate']; ?></td>
                                    <td style="text-align:right;">&#163;<?php echo $resource['total']; ?></td>
                                    <!--
                                    <td><a href="<?php echo $this->url('resource_activity', array('rid' => $resource['id'], 'action' => 'edit')) ?>" class="btn btn-success"><i class="icon-pencil"></i></a></td>
                                    -->
                                    <td>
                                        <?php if ( $resource['reference_type'] == 'product' ): ?>
                                            <a href="javascript:;" data-value="<?php echo $resource['id']; ?>" class="btn btn-success btn-edit-product"><i class="icon-pencil"></i></a>
                                        <?php elseif ( $resource['reference_type'] == 'invoice' ): ?>
                                            <a href="javascript:;" data-value="<?php echo $resource['id']; ?>" class="btn btn-success btn-edit-invoice"><i class="icon-pencil"></i></a>
                                        <?php else: ?>
                                            <a href="javascript:;" data-value="<?php echo $resource['id']; ?>" class="btn btn-success btn-edit-activity"><i class="icon-pencil"></i></a>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr>
                                <td colspan="11" style="text-align:center;">No Record found</td>
                            </tr>
                        <?php endif; ?>
                        <tr>
                            <td colspan="11">
                                <div class="paging text-right">
                                    <?php $paging = $this->paginationHelper($total_rows, $page, $base_path, 10);
                                    echo $paging;
                                    ?>
                                </div>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
    <!-- END EXAMPLE TABLE widget-->
</div>
</div>

<?php echo $this->partial('partial/resource/resource_add.phtml'); ?>
<?php echo $this->partial('partial/resource/resource_edit.phtml'); ?>

<?php echo $this->partial('partial/resource/product_add.phtml'); ?>
<?php echo $this->partial('partial/resource/product_edit.phtml'); ?>

<?php echo $this->partial('partial/resource/invoice_add.phtml'); ?>
<?php echo $this->partial('partial/resource/invoice_edit.phtml'); ?>
