<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN ORDERED LISTS PORTLET-->
        <div class="widget orange">
            <div class="widget-title">
                <h4><i class="icon-eye-open"></i> <?php echo $title; ?> Report</h4>
                <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
                <a href="javascript:;" class="icon-remove"></a>
                </span>
            </div>
            <div class="widget-body relative">
                <div id="reportLoader" class="loader"></div>
                <h4><?php echo $title; ?> Report</h4>
                <!-- BEGIN REPORT PARTIAL-->
                <?php if( $this->flashMessenger()->render('success') ): ?>
                <div class="row-fluid">
                    <div class="span12">
                        <div class="alert alert-success"><?php echo $this->flashMessenger()->render('success'); ?></div>
                    </div>
                </div>
                <?php endif; ?>
                <?php echo $this->partial( 'partial/report/rating/' . $partialScript . '.phtml' ); ?>
                <!-- END  REPORT PARTIAL-->
            </div>
        </div>
        <!-- END ORDERED LISTS PORTLET-->

    </div>
</div>