<?php
$this->inlineScript()
    ->appendFile('/js/forms/project/notes.js?31032015')
        ;

$route = ($project->getType()->getTypeId()==3)?'trial':((($project->getStatus()->getJob()==1) || (($project->getStatus()->getJob()==0)&&($project->getStatus()->getWeighting()==1)&&($project->getStatus()->getHalt()==1)))?'job':'project');

?><div id="myModalAddNote" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel4" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Add Note&nbsp;</h3>
    </div>
    <div class="modal-body">
        <div id="noteLoader" class="loader"></div>
        <p>
            Enter the note that you would like to add to the project in the box provided and then click on the Add Note button.
        </p>
        <div class="control-group">
            <div class="controls">
                <form id="AddNoteForm" action="/client-<?php echo $project->getClient()->getClientId(); ?>/<?php echo $route.'-'.$project->getProjectId(); ?>/addnote/" class="form-horizontal form-nomargin"> 
                <div class="control-group">
                    <textarea class="span12" name="note" placeholder="enter your note here"></textarea>
                </div>
                <div class="control-group">
                    <label class="control-label">Type of note:</label>
                    <div class="controls">
                        <select class="span12" name="nscope">
                            <option value="1">General Note (default)</option>
                            <option value="2">Delivery Note</option>
                        </select>
                    </div>
                </div>
                </form>
            </div>
        </div>   
        <div id="msgs3"></div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Cancel</button>
        <button class="btn btn-success" id="btn-save-note" aria-hidden="true"><i class="icon-plus"></i> Add Note</button>
    </div>
</div>

<div id="myModalEditNote" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel4" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Edit Note&nbsp;</h3>
    </div>
    <div class="modal-body">
        <div id="noteEditLoader" class="loader"></div>
        <p>
            Edit the note in the box provided and then click on the Edit Note button.
        </p>
        <div class="control-group">
            <div class="controls">
                <form id="EditNoteForm" action="/client-<?php echo $project->getClient()->getClientId(); ?>/<?php echo $route.'-'.$project->getProjectId(); ?>/editnote/" class="form-horizontal form-nomargin">
                    <div class="control-group">
                        <textarea class="span12" name="note" placeholder="enter your note here"></textarea>
                        <input type="hidden" name="note_idx" id="note_idx" />
                    </div>
                    <div class="control-group">
                        <label class="control-label">Type of note:</label>
                        <div class="controls">
                            <select class="span12" name="nscope" id="nscope_edit">
                                <option value="1">General Note (default)</option>
                                <option value="2">Delivery Note</option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div id="msgs3"></div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Cancel</button>
        <button class="btn btn-success" id="btn-edit-note" aria-hidden="true"><i class="icon-plus"></i> Edit Note</button>
    </div>
</div>