<?php
$this->inlineScript()
    ->appendFile( 'https://code.highcharts.com/highcharts.js' )
    ->appendFile( 'https://code.highcharts.com/modules/exporting.js' );

$this->inlineScript()->captureStart();
echo <<<JS
$('.project-status').on('click', function (e) {
        $('#modalProjectStatus').modal();
});

$(function () {
    $('#sales-chart-container').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Stacked column chart'
        },
        xAxis: {
            categories: ['Apples', 'Oranges', 'Pears', 'Grapes', 'Bananas']
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Total fruit consumption'
            },
            stackLabels: {
                enabled: true,
                style: {
                    fontWeight: 'bold',
                    color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                }
            }
        },
        legend: {
            align: 'right',
            x: -30,
            verticalAlign: 'top',
            y: 25,
            floating: true,
            backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
            borderColor: '#CCC',
            borderWidth: 1,
            shadow: false
        },
        tooltip: {
            headerFormat: '<b>{point.x}</b><br/>',
            pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}'
        },
        plotOptions: {
            column: {
                stacking: 'normal',
                dataLabels: {
                    enabled: true,
                    color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white',
                    style: {
                        textShadow: '0 0 3px black'
                    }
                }
            }
        },
        series: [{
            name: 'John',
            data: [5, 3, 4, 7, 2]
        }, {
            name: 'Jane',
            data: [2, 2, 3, 2, 1]
        }, {
            name: 'Joe',
            data: [3, 4, 4, 2, 5]
        }]
    });
});
JS;

$this->inlineScript()->captureEnd();
?>
<div class="row-fluid">
    <div class="span12">
        <a class="btn btn-success  pull-right" href="<?php echo $this->url( 'ratingreport', array( 'action' => 'export', 'rating' => $rating, 'user' => $user_id ) ); ?>">Download CSV</a>
    </div>
</div>
    <table class="table table-bordered">
    <tr>
        <th>Rating</th>
        <th>Reference</th>
        <th>Project</th>
        <th>Customer</th>
        <th>Project Value</th>
        <!--
        <th>Margin</th>
        -->
        <th>Owner</th>
        <th>Added</th>
        <th>Expected</th>
    </tr>
    <?php if ( !empty($data) ): ?>
        <?php $total = 0; ?>
        <?php foreach ( $data as $key => $value ): ?>
            <tr>
                <?php
                    $ratingColor = '#fff';
                    switch ( $value['rating'] )
                    {
                        case 0: // Unrated
                            $ratingColor = '#ccc';
                            break;
                        case 1: // Red Rated
                            $ratingColor = '#DE577B';
                            break;
                        case 2: // Amber Rated
                            $ratingColor = '#F37B53';
                            break;
                        case 3: // Green Rated
                            $ratingColor = '#0CA389';
                            break;
                        default:
                            $ratingColor = '#fff';
                    }
                ?>
                <td style="background-color:<?php echo $ratingColor; ?>;text-align:center;color:#fff;">
                    <strong>
                        <?php
                            if( $value['project_status_id'] == 1 )
                            {
                                echo 'P';
                            }
                            elseif( $value['project_status_id'] >= 40 && $value['project_satus_id'] <= 100 )
                            {
                                echo 'J';
                            }
                            elseif( $value['project_status_id'] == 600 )
                            {
                                echo 'L';
                            }
                        ?>
                    </strong>
                </td>
                <td nowrap="nowrap"><?php echo str_pad( $value['client_id'], 5, "0", STR_PAD_LEFT ) . '-' . str_pad( $value['project_id'], 5, "0", STR_PAD_LEFT ) ?></td>
                <td><a href="<?php echo $this->url( 'project', Array( 'cid' => $value['client_id'], 'pid' => $value['project_id'] ) ); ?>"> <?php echo $value['project_name'] ?></a></td>
                <td><a href="<?php echo $this->url( 'client', Array( 'id' => $value['client_id'] ) ); ?>"><?php echo $value['client_name']; ?></a></td>
                <td style="text-align:right !important;">&#163; <?php echo number_format( $value['price'], 2 ); ?></td>
                <!--
                <td nowrap="nowrap">
                    <?php /*
                    $tmpPpuTotal = $value['figures']['cost'];
                    $tmpCpuTotal = $value['cost'];
                    $prjMargin   = (($tmpPpuTotal - $tmpCpuTotal) / $tmpPpuTotal) * 100;
                    echo number_format( $prjMargin, 2 ) . " %";
*/
                ?>
                </td>
                -->
                <td><?php echo $value['user_name']; ?></td>
                <td nowrap="nowrap"><?php echo date( 'd M, Y', strtotime( $value['created'] ) ); ?></td>
                <td nowrap="nowrap"><?php echo empty($value['expected_date']) ? 'Date not set' : date( 'd M, Y', strtotime( $value['expected_date'] ) ); ?></td>
            </tr>
            <?php $total += $value['price']; ?>
        <?php endforeach; ?>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td style="text-align:right;"><strong>Total Value</strong></td>
            <td style="text-align:right;">&#163;<?php echo number_format( $total, 2 ); ?></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>

    <?php else: ?>
        <tr>
            <td colspan="8">
                No record found
            </td>
        </tr>
    <?php endif; ?>
</table>